"""init

Revision ID: 0808d5187562
Revises: 
Create Date: 2026-06-30 22:17:49.163778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0808d5187562'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('ipv4', sa.String(length=64), nullable=True),
    sa.Column('shortname', sa.String(length=255), nullable=True),
    sa.Column('fqdn', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('os_family', sa.String(length=100), nullable=True),
    sa.Column('os_distro', sa.String(length=100), nullable=True),
    sa.Column('kernel_version', sa.String(length=255), nullable=True),
    sa.Column('arch', sa.String(length=50), nullable=True),
    sa.Column('cpus', sa.Integer(), nullable=True),
    sa.Column('memory_mb', sa.BigInteger(), nullable=True),
    sa.Column('storage_total_gb', sa.BigInteger(), nullable=True),
    sa.Column('storage_used_gb', sa.BigInteger(), nullable=True),
    sa.Column('available_security_fixes', sa.Integer(), nullable=True),
    sa.Column('available_bugfixes', sa.Integer(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    op.create_table('daemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_user', sa.String(length=100), nullable=True),
    sa.Column('start_group', sa.String(length=100), nullable=True),
    sa.Column('unit_file_path', sa.String(length=500), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('sub_state', sa.String(length=50), nullable=True),
    sa.Column('exec_start', sa.String(length=1000), nullable=True),
    sa.Column('exec_stop', sa.String(length=1000), nullable=True),
    sa.Column('exec_reload', sa.String(length=1000), nullable=True),
    sa.Column('restart_policy', sa.String(length=50), nullable=True),
    sa.Column('restart_sec', sa.Integer(), nullable=True),
    sa.Column('timeout_sec', sa.Integer(), nullable=True),
    sa.Column('working_directory', sa.String(length=500), nullable=True),
    sa.Column('wants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'name', name='uq_daemon_host_name')
    )
    op.create_table('disks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('disk_path', sa.String(length=255), nullable=True),
    sa.Column('size_gb', sa.BigInteger(), nullable=False),
    sa.Column('fstype', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('boot_disk', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'disk_path', name='uq_disk_host_path')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'name', name='uq_group_host_name')
    )
    op.create_table('mounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('mountpoint', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('fstype', sa.String(length=100), nullable=True),
    sa.Column('opts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('in_fstab', sa.Boolean(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.BigInteger(), nullable=True),
    sa.Column('used_pct', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'mountpoint', name='uq_mount_host_mp')
    )
    op.create_table('nics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('ipv4', sa.String(length=64), nullable=True),
    sa.Column('ipv6', sa.String(length=128), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'mac_address', name='uq_nic_host_mac')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('release', sa.String(length=255), nullable=True),
    sa.Column('arch', sa.String(length=50), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('installtime', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'name', 'version', 'release', 'arch', name='uq_pkg_host_nvra')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('pgroup', sa.String(length=255), nullable=True),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_sudo', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'uid', name='uq_user_host_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('packages')
    op.drop_table('nics')
    op.drop_table('mounts')
    op.drop_table('groups')
    op.drop_table('disks')
    op.drop_table('daemons')
    op.drop_table('hosts')
    # ### end Alembic commands ###
