"""sync failure warning flag

Revision ID: cd951819de7f
Revises: e977360bf739
Create Date: 2026-08-10 20:40:33.393763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd951819de7f'
down_revision: Union[str, Sequence[str], None] = 'e977360bf739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_failures', sa.Column('is_warning', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_failures', 'is_warning')
    # ### end Alembic commands ###
