"""sync run audit and failure tracking

Revision ID: e977360bf739
Revises: bc45eba301a8
Create Date: 2026-08-10 19:18:21.379232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e977360bf739'
down_revision: Union[str, Sequence[str], None] = 'bc45eba301a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invoked_by', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('total_hosts', sa.Integer(), nullable=True),
    sa.Column('failed_hosts', sa.Integer(), nullable=True),
    sa.Column('exit_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_failures_host_id'), 'sync_failures', ['host_id'], unique=False)
    op.create_index(op.f('ix_sync_failures_sync_run_id'), 'sync_failures', ['sync_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_failures_sync_run_id'), table_name='sync_failures')
    op.drop_index(op.f('ix_sync_failures_host_id'), table_name='sync_failures')
    op.drop_table('sync_failures')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
