"""satellite errata fields

Revision ID: 35d814db83cb
Revises: 51372bd54bff
Create Date: 2026-08-08 17:54:23.389248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d814db83cb'
down_revision: Union[str, Sequence[str], None] = '51372bd54bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('foreman_id', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('errata_count', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('rhsa_count', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('rhsa_critical', sa.Integer(), nullable=True))
    op.add_column('hosts', sa.Column('rhsa_important', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'rhsa_important')
    op.drop_column('hosts', 'rhsa_critical')
    op.drop_column('hosts', 'rhsa_count')
    op.drop_column('hosts', 'errata_count')
    op.drop_column('hosts', 'foreman_id')
    # ### end Alembic commands ###
