"""empty message

Revision ID: 51372bd54bff
Revises: abd9c2115517
Create Date: 2026-08-07 19:21:04.974329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51372bd54bff'
down_revision: Union[str, Sequence[str], None] = 'abd9c2115517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('os_major', sa.String(), nullable=True))
    op.add_column('hosts', sa.Column('os_minor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'os_minor')
    op.drop_column('hosts', 'os_major')
    # ### end Alembic commands ###
