"""foreman registered flag

Revision ID: 84fab2b1042e
Revises: 35d814db83cb
Create Date: 2026-08-08 18:35:31.500829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fab2b1042e'
down_revision: Union[str, Sequence[str], None] = '35d814db83cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('foreman_registered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'foreman_registered')
    # ### end Alembic commands ###
