"""host machine id

Revision ID: a256c9ae5436
Revises: 84fab2b1042e
Create Date: 2026-08-08 18:43:50.046002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a256c9ae5436'
down_revision: Union[str, Sequence[str], None] = '84fab2b1042e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('machine_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'hosts', ['machine_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hosts', type_='unique')
    op.drop_column('hosts', 'machine_id')
    # ### end Alembic commands ###
