CREATE TABLE core.daemons (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vm_id int NOT NULL REFERENCES core.vms(id),
    daemon_name varchar(255) NOT NULL,
    start_user varchar(255),
    start_group varchar(255),
    unit_file_path varchar(1024),
    service_type varchar(50),
    service_state varchar(50),
    service_sub_state varchar(50),
    exec_start text,
    exec_stop text,
    exec_reload text,
    restart_policy varchar(50),
    restart_sec int,
    timeout_sec int,
    working_directory varchar(1024),
    wants text[],
    requires text[],
    after text[],
    before text[],
    enabled boolean DEFAULT false,
    active boolean DEFAULT false,
    metadata jsonb NULL,
    constraint unique_daemons_vm_daemon unique (vm_id, daemon_name)
);